---
resources:
- name: demoapp
  type: git
  source:
    uri: https://github.com/virajago/pcf-pipeline.git
jobs:
- name: unit-test-app
  serial: true
  public: true
  plan:
  - get: demoapp
  - task: task-test-app
    file: demoapp/ci/unit_test_app.yml
