---
resources:
- name: demoapp
  type: git
  source:
    uri: https://github.com/virajago/pcf-pipeline.git
- name: buildrepo
  type: git
  source:
    uri: https://github.com/virajago/pcf-pipeline-build.git
- name: cf-dev-resource
  type: cf
  source:
    api: https://api.run.pivotal.io/
    username: vrajagopal@pivotal.io
    password: {{cf-password}}
    organization: EMEA
    space: vj-dev
    skip_cert_check: true
- name: cf-test-resource
  type: cf
  source:
    api: https://api.run.pivotal.io/
    username: vrajagopal@pivotal.io
    password: {{cf-password}}
    organization: EMEA
    space: vj-test
    skip_cert_check: true
- name: cf-uat-resource
  type: cf
  source:
    api: https://api.run.pivotal.io/
    username: vrajagopal@pivotal.io
    password: {{cf-password}}
    organization: EMEA
    space: vj-uat
    skip_cert_check: true

jobs:
- name: unit-test-app
  serial: true
  public: true
  plan:
  - get: demoapp
    trigger: true
  - task: task-test-app
    file: demoapp/ci/unit_test_app.yml
- name: build-app
  serial: true
  public: true
  plan:
  - get: demoapp
    passed: [unit-test-app]
    trigger: true
  - task: task-build-app
    file: demoapp/ci/build_app.yml
- name: deploy-pcf-dev
  serial: true
  public: true
  plan:
  - get: buildrepo
    trigger: true
    passed: [build-app]
  - get: demoapp
    passed: [build-app]
    trigger: true
  - put: cf-dev-resource
    params:
      manifest: demoapp/ci/manifest-dev.yml
      path: ./buildrepo/demoapp-*.jar
      current_app_name: vj-demoapp-dev
- name: deploy-pcf-test
  serial: true
  public: true
  plan:
  - get: buildrepo
    trigger: true
    passed: [deploy-pcf-dev]
  - get: demoapp
    passed: [deploy-pcf-dev]
    trigger: true
  - put: cf-test-resource
    params:
      manifest: demoapp/ci/manifest-test.yml
      path: ./buildrepo/demoapp-*.jar
      current_app_name: vj-demoapp-test
- name: qa-test-app
  serial: true
  public: true
  plan:
  - get: demoapp
    passed: [deploy-pcf-test]
    trigger: true
  - task: task-qa-test-app
    file: demoapp/ci/qa_test_app.yml
- name: deploy-pcf-uat
  serial: true
  public: true
  plan:
  - get: buildrepo
    trigger: true
  - get: demoapp
    passed: [qa-test-app]
    trigger: true
  - put: cf-uat-resource
    params:
      manifest: demoapp/ci/manifest-uat.yml
      path: ./buildrepo/demoapp-*.jar
      current_app_name: vj-demoapp-uat
